name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js (NPM registry)
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn build
      - name: Yarn Package Publish
        uses: luvies/action-yarn-publish@v0.1.1
        # with:
        #   git-tag: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
